version: '3'
services:
  universal_app:
    build: ./
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
    volumes:
      - ./pages:/usr/src/app/pages
      - ./shared:/usr/src/app/shared
